dir: ""
filename: '{{ .InterfaceFile | base | trimSuffix ".go" }}_moq_test.go'
structname: 'Moq{{ .InterfaceName | trimSuffix "Interface" }}'
template: "matryer"
template-data:
  stub-impl: true
  with-resets: true
packages:
  "github.com/dsh2dsh/goimapnotify/internal/imap":
    interfaces:
      "IMAPClientInterface":
      "IMAPDialer":
      "WatchClientInterface":
