// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package imap

import (
	"crypto/tls"
	"io"
	"sync"
	"time"

	"github.com/emersion/go-imap"
	"github.com/emersion/go-imap/client"
	"github.com/emersion/go-sasl"
)

// Ensure that MoqIMAPClient does implement IMAPClientInterface.
// If this is not the case, regenerate this file with mockery.
var _ IMAPClientInterface = &MoqIMAPClient{}

// MoqIMAPClient is a mock implementation of IMAPClientInterface.
//
//	func TestSomethingThatUsesIMAPClientInterface(t *testing.T) {
//
//		// make and configure a mocked IMAPClientInterface
//		mockedIMAPClientInterface := &MoqIMAPClient{
//			AuthenticateFunc: func(auth sasl.Client) error {
//				panic("mock out the Authenticate method")
//			},
//			LoggedOutFunc: func() <-chan struct{} {
//				panic("mock out the LoggedOut method")
//			},
//			LoginFunc: func(username string, password string) error {
//				panic("mock out the Login method")
//			},
//			LogoutFunc: func() error {
//				panic("mock out the Logout method")
//			},
//			SelectFunc: func(name string, readOnly bool) (*imap.MailboxStatus, error) {
//				panic("mock out the Select method")
//			},
//			SetDebugFunc: func(w io.Writer)  {
//				panic("mock out the SetDebug method")
//			},
//			StartTLSFunc: func(config *tls.Config) error {
//				panic("mock out the StartTLS method")
//			},
//			SupportFunc: func(capability string) (bool, error) {
//				panic("mock out the Support method")
//			},
//			SupportAuthFunc: func(mech string) (bool, error) {
//				panic("mock out the SupportAuth method")
//			},
//		}
//
//		// use mockedIMAPClientInterface in code that requires IMAPClientInterface
//		// and then make assertions.
//
//	}
type MoqIMAPClient struct {
	// AuthenticateFunc mocks the Authenticate method.
	AuthenticateFunc func(auth sasl.Client) error

	// LoggedOutFunc mocks the LoggedOut method.
	LoggedOutFunc func() <-chan struct{}

	// LoginFunc mocks the Login method.
	LoginFunc func(username string, password string) error

	// LogoutFunc mocks the Logout method.
	LogoutFunc func() error

	// SelectFunc mocks the Select method.
	SelectFunc func(name string, readOnly bool) (*imap.MailboxStatus, error)

	// SetDebugFunc mocks the SetDebug method.
	SetDebugFunc func(w io.Writer)

	// StartTLSFunc mocks the StartTLS method.
	StartTLSFunc func(config *tls.Config) error

	// SupportFunc mocks the Support method.
	SupportFunc func(capability string) (bool, error)

	// SupportAuthFunc mocks the SupportAuth method.
	SupportAuthFunc func(mech string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Authenticate holds details about calls to the Authenticate method.
		Authenticate []struct {
			// Auth is the auth argument value.
			Auth sasl.Client
		}
		// LoggedOut holds details about calls to the LoggedOut method.
		LoggedOut []struct {
		}
		// Login holds details about calls to the Login method.
		Login []struct {
			// Username is the username argument value.
			Username string
			// Password is the password argument value.
			Password string
		}
		// Logout holds details about calls to the Logout method.
		Logout []struct {
		}
		// Select holds details about calls to the Select method.
		Select []struct {
			// Name is the name argument value.
			Name string
			// ReadOnly is the readOnly argument value.
			ReadOnly bool
		}
		// SetDebug holds details about calls to the SetDebug method.
		SetDebug []struct {
			// W is the w argument value.
			W io.Writer
		}
		// StartTLS holds details about calls to the StartTLS method.
		StartTLS []struct {
			// Config is the config argument value.
			Config *tls.Config
		}
		// Support holds details about calls to the Support method.
		Support []struct {
			// Capability is the capability argument value.
			Capability string
		}
		// SupportAuth holds details about calls to the SupportAuth method.
		SupportAuth []struct {
			// Mech is the mech argument value.
			Mech string
		}
	}
	lockAuthenticate sync.RWMutex
	lockLoggedOut    sync.RWMutex
	lockLogin        sync.RWMutex
	lockLogout       sync.RWMutex
	lockSelect       sync.RWMutex
	lockSetDebug     sync.RWMutex
	lockStartTLS     sync.RWMutex
	lockSupport      sync.RWMutex
	lockSupportAuth  sync.RWMutex
}

// Authenticate calls AuthenticateFunc.
func (mock *MoqIMAPClient) Authenticate(auth sasl.Client) error {
	callInfo := struct {
		Auth sasl.Client
	}{
		Auth: auth,
	}
	mock.lockAuthenticate.Lock()
	mock.calls.Authenticate = append(mock.calls.Authenticate, callInfo)
	mock.lockAuthenticate.Unlock()
	if mock.AuthenticateFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.AuthenticateFunc(auth)
}

// AuthenticateCalls gets all the calls that were made to Authenticate.
// Check the length with:
//
//	len(mockedIMAPClientInterface.AuthenticateCalls())
func (mock *MoqIMAPClient) AuthenticateCalls() []struct {
	Auth sasl.Client
} {
	var calls []struct {
		Auth sasl.Client
	}
	mock.lockAuthenticate.RLock()
	calls = mock.calls.Authenticate
	mock.lockAuthenticate.RUnlock()
	return calls
}

// ResetAuthenticateCalls reset all the calls that were made to Authenticate.
func (mock *MoqIMAPClient) ResetAuthenticateCalls() {
	mock.lockAuthenticate.Lock()
	mock.calls.Authenticate = nil
	mock.lockAuthenticate.Unlock()
}

// LoggedOut calls LoggedOutFunc.
func (mock *MoqIMAPClient) LoggedOut() <-chan struct{} {
	callInfo := struct {
	}{}
	mock.lockLoggedOut.Lock()
	mock.calls.LoggedOut = append(mock.calls.LoggedOut, callInfo)
	mock.lockLoggedOut.Unlock()
	if mock.LoggedOutFunc == nil {
		var (
			valCh <-chan struct{}
		)
		return valCh
	}
	return mock.LoggedOutFunc()
}

// LoggedOutCalls gets all the calls that were made to LoggedOut.
// Check the length with:
//
//	len(mockedIMAPClientInterface.LoggedOutCalls())
func (mock *MoqIMAPClient) LoggedOutCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLoggedOut.RLock()
	calls = mock.calls.LoggedOut
	mock.lockLoggedOut.RUnlock()
	return calls
}

// ResetLoggedOutCalls reset all the calls that were made to LoggedOut.
func (mock *MoqIMAPClient) ResetLoggedOutCalls() {
	mock.lockLoggedOut.Lock()
	mock.calls.LoggedOut = nil
	mock.lockLoggedOut.Unlock()
}

// Login calls LoginFunc.
func (mock *MoqIMAPClient) Login(username string, password string) error {
	callInfo := struct {
		Username string
		Password string
	}{
		Username: username,
		Password: password,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	if mock.LoginFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.LoginFunc(username, password)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedIMAPClientInterface.LoginCalls())
func (mock *MoqIMAPClient) LoginCalls() []struct {
	Username string
	Password string
} {
	var calls []struct {
		Username string
		Password string
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}

// ResetLoginCalls reset all the calls that were made to Login.
func (mock *MoqIMAPClient) ResetLoginCalls() {
	mock.lockLogin.Lock()
	mock.calls.Login = nil
	mock.lockLogin.Unlock()
}

// Logout calls LogoutFunc.
func (mock *MoqIMAPClient) Logout() error {
	callInfo := struct {
	}{}
	mock.lockLogout.Lock()
	mock.calls.Logout = append(mock.calls.Logout, callInfo)
	mock.lockLogout.Unlock()
	if mock.LogoutFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.LogoutFunc()
}

// LogoutCalls gets all the calls that were made to Logout.
// Check the length with:
//
//	len(mockedIMAPClientInterface.LogoutCalls())
func (mock *MoqIMAPClient) LogoutCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLogout.RLock()
	calls = mock.calls.Logout
	mock.lockLogout.RUnlock()
	return calls
}

// ResetLogoutCalls reset all the calls that were made to Logout.
func (mock *MoqIMAPClient) ResetLogoutCalls() {
	mock.lockLogout.Lock()
	mock.calls.Logout = nil
	mock.lockLogout.Unlock()
}

// Select calls SelectFunc.
func (mock *MoqIMAPClient) Select(name string, readOnly bool) (*imap.MailboxStatus, error) {
	callInfo := struct {
		Name     string
		ReadOnly bool
	}{
		Name:     name,
		ReadOnly: readOnly,
	}
	mock.lockSelect.Lock()
	mock.calls.Select = append(mock.calls.Select, callInfo)
	mock.lockSelect.Unlock()
	if mock.SelectFunc == nil {
		var (
			mailboxStatus *imap.MailboxStatus
			err           error
		)
		return mailboxStatus, err
	}
	return mock.SelectFunc(name, readOnly)
}

// SelectCalls gets all the calls that were made to Select.
// Check the length with:
//
//	len(mockedIMAPClientInterface.SelectCalls())
func (mock *MoqIMAPClient) SelectCalls() []struct {
	Name     string
	ReadOnly bool
} {
	var calls []struct {
		Name     string
		ReadOnly bool
	}
	mock.lockSelect.RLock()
	calls = mock.calls.Select
	mock.lockSelect.RUnlock()
	return calls
}

// ResetSelectCalls reset all the calls that were made to Select.
func (mock *MoqIMAPClient) ResetSelectCalls() {
	mock.lockSelect.Lock()
	mock.calls.Select = nil
	mock.lockSelect.Unlock()
}

// SetDebug calls SetDebugFunc.
func (mock *MoqIMAPClient) SetDebug(w io.Writer) {
	callInfo := struct {
		W io.Writer
	}{
		W: w,
	}
	mock.lockSetDebug.Lock()
	mock.calls.SetDebug = append(mock.calls.SetDebug, callInfo)
	mock.lockSetDebug.Unlock()
	if mock.SetDebugFunc == nil {
		return
	}
	mock.SetDebugFunc(w)
}

// SetDebugCalls gets all the calls that were made to SetDebug.
// Check the length with:
//
//	len(mockedIMAPClientInterface.SetDebugCalls())
func (mock *MoqIMAPClient) SetDebugCalls() []struct {
	W io.Writer
} {
	var calls []struct {
		W io.Writer
	}
	mock.lockSetDebug.RLock()
	calls = mock.calls.SetDebug
	mock.lockSetDebug.RUnlock()
	return calls
}

// ResetSetDebugCalls reset all the calls that were made to SetDebug.
func (mock *MoqIMAPClient) ResetSetDebugCalls() {
	mock.lockSetDebug.Lock()
	mock.calls.SetDebug = nil
	mock.lockSetDebug.Unlock()
}

// StartTLS calls StartTLSFunc.
func (mock *MoqIMAPClient) StartTLS(config *tls.Config) error {
	callInfo := struct {
		Config *tls.Config
	}{
		Config: config,
	}
	mock.lockStartTLS.Lock()
	mock.calls.StartTLS = append(mock.calls.StartTLS, callInfo)
	mock.lockStartTLS.Unlock()
	if mock.StartTLSFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.StartTLSFunc(config)
}

// StartTLSCalls gets all the calls that were made to StartTLS.
// Check the length with:
//
//	len(mockedIMAPClientInterface.StartTLSCalls())
func (mock *MoqIMAPClient) StartTLSCalls() []struct {
	Config *tls.Config
} {
	var calls []struct {
		Config *tls.Config
	}
	mock.lockStartTLS.RLock()
	calls = mock.calls.StartTLS
	mock.lockStartTLS.RUnlock()
	return calls
}

// ResetStartTLSCalls reset all the calls that were made to StartTLS.
func (mock *MoqIMAPClient) ResetStartTLSCalls() {
	mock.lockStartTLS.Lock()
	mock.calls.StartTLS = nil
	mock.lockStartTLS.Unlock()
}

// Support calls SupportFunc.
func (mock *MoqIMAPClient) Support(capability string) (bool, error) {
	callInfo := struct {
		Capability string
	}{
		Capability: capability,
	}
	mock.lockSupport.Lock()
	mock.calls.Support = append(mock.calls.Support, callInfo)
	mock.lockSupport.Unlock()
	if mock.SupportFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.SupportFunc(capability)
}

// SupportCalls gets all the calls that were made to Support.
// Check the length with:
//
//	len(mockedIMAPClientInterface.SupportCalls())
func (mock *MoqIMAPClient) SupportCalls() []struct {
	Capability string
} {
	var calls []struct {
		Capability string
	}
	mock.lockSupport.RLock()
	calls = mock.calls.Support
	mock.lockSupport.RUnlock()
	return calls
}

// ResetSupportCalls reset all the calls that were made to Support.
func (mock *MoqIMAPClient) ResetSupportCalls() {
	mock.lockSupport.Lock()
	mock.calls.Support = nil
	mock.lockSupport.Unlock()
}

// SupportAuth calls SupportAuthFunc.
func (mock *MoqIMAPClient) SupportAuth(mech string) (bool, error) {
	callInfo := struct {
		Mech string
	}{
		Mech: mech,
	}
	mock.lockSupportAuth.Lock()
	mock.calls.SupportAuth = append(mock.calls.SupportAuth, callInfo)
	mock.lockSupportAuth.Unlock()
	if mock.SupportAuthFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.SupportAuthFunc(mech)
}

// SupportAuthCalls gets all the calls that were made to SupportAuth.
// Check the length with:
//
//	len(mockedIMAPClientInterface.SupportAuthCalls())
func (mock *MoqIMAPClient) SupportAuthCalls() []struct {
	Mech string
} {
	var calls []struct {
		Mech string
	}
	mock.lockSupportAuth.RLock()
	calls = mock.calls.SupportAuth
	mock.lockSupportAuth.RUnlock()
	return calls
}

// ResetSupportAuthCalls reset all the calls that were made to SupportAuth.
func (mock *MoqIMAPClient) ResetSupportAuthCalls() {
	mock.lockSupportAuth.Lock()
	mock.calls.SupportAuth = nil
	mock.lockSupportAuth.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *MoqIMAPClient) ResetCalls() {
	mock.lockAuthenticate.Lock()
	mock.calls.Authenticate = nil
	mock.lockAuthenticate.Unlock()

	mock.lockLoggedOut.Lock()
	mock.calls.LoggedOut = nil
	mock.lockLoggedOut.Unlock()

	mock.lockLogin.Lock()
	mock.calls.Login = nil
	mock.lockLogin.Unlock()

	mock.lockLogout.Lock()
	mock.calls.Logout = nil
	mock.lockLogout.Unlock()

	mock.lockSelect.Lock()
	mock.calls.Select = nil
	mock.lockSelect.Unlock()

	mock.lockSetDebug.Lock()
	mock.calls.SetDebug = nil
	mock.lockSetDebug.Unlock()

	mock.lockStartTLS.Lock()
	mock.calls.StartTLS = nil
	mock.lockStartTLS.Unlock()

	mock.lockSupport.Lock()
	mock.calls.Support = nil
	mock.lockSupport.Unlock()

	mock.lockSupportAuth.Lock()
	mock.calls.SupportAuth = nil
	mock.lockSupportAuth.Unlock()
}

// Ensure that MoqIMAPDialer does implement IMAPDialer.
// If this is not the case, regenerate this file with mockery.
var _ IMAPDialer = &MoqIMAPDialer{}

// MoqIMAPDialer is a mock implementation of IMAPDialer.
//
//	func TestSomethingThatUsesIMAPDialer(t *testing.T) {
//
//		// make and configure a mocked IMAPDialer
//		mockedIMAPDialer := &MoqIMAPDialer{
//			DialFunc: func(addr string) (IMAPClientInterface, error) {
//				panic("mock out the Dial method")
//			},
//			DialTLSFunc: func(addr string, config *tls.Config) (IMAPClientInterface, error) {
//				panic("mock out the DialTLS method")
//			},
//		}
//
//		// use mockedIMAPDialer in code that requires IMAPDialer
//		// and then make assertions.
//
//	}
type MoqIMAPDialer struct {
	// DialFunc mocks the Dial method.
	DialFunc func(addr string) (IMAPClientInterface, error)

	// DialTLSFunc mocks the DialTLS method.
	DialTLSFunc func(addr string, config *tls.Config) (IMAPClientInterface, error)

	// calls tracks calls to the methods.
	calls struct {
		// Dial holds details about calls to the Dial method.
		Dial []struct {
			// Addr is the addr argument value.
			Addr string
		}
		// DialTLS holds details about calls to the DialTLS method.
		DialTLS []struct {
			// Addr is the addr argument value.
			Addr string
			// Config is the config argument value.
			Config *tls.Config
		}
	}
	lockDial    sync.RWMutex
	lockDialTLS sync.RWMutex
}

// Dial calls DialFunc.
func (mock *MoqIMAPDialer) Dial(addr string) (IMAPClientInterface, error) {
	callInfo := struct {
		Addr string
	}{
		Addr: addr,
	}
	mock.lockDial.Lock()
	mock.calls.Dial = append(mock.calls.Dial, callInfo)
	mock.lockDial.Unlock()
	if mock.DialFunc == nil {
		var (
			iMAPClientInterface IMAPClientInterface
			err                 error
		)
		return iMAPClientInterface, err
	}
	return mock.DialFunc(addr)
}

// DialCalls gets all the calls that were made to Dial.
// Check the length with:
//
//	len(mockedIMAPDialer.DialCalls())
func (mock *MoqIMAPDialer) DialCalls() []struct {
	Addr string
} {
	var calls []struct {
		Addr string
	}
	mock.lockDial.RLock()
	calls = mock.calls.Dial
	mock.lockDial.RUnlock()
	return calls
}

// ResetDialCalls reset all the calls that were made to Dial.
func (mock *MoqIMAPDialer) ResetDialCalls() {
	mock.lockDial.Lock()
	mock.calls.Dial = nil
	mock.lockDial.Unlock()
}

// DialTLS calls DialTLSFunc.
func (mock *MoqIMAPDialer) DialTLS(addr string, config *tls.Config) (IMAPClientInterface, error) {
	callInfo := struct {
		Addr   string
		Config *tls.Config
	}{
		Addr:   addr,
		Config: config,
	}
	mock.lockDialTLS.Lock()
	mock.calls.DialTLS = append(mock.calls.DialTLS, callInfo)
	mock.lockDialTLS.Unlock()
	if mock.DialTLSFunc == nil {
		var (
			iMAPClientInterface IMAPClientInterface
			err                 error
		)
		return iMAPClientInterface, err
	}
	return mock.DialTLSFunc(addr, config)
}

// DialTLSCalls gets all the calls that were made to DialTLS.
// Check the length with:
//
//	len(mockedIMAPDialer.DialTLSCalls())
func (mock *MoqIMAPDialer) DialTLSCalls() []struct {
	Addr   string
	Config *tls.Config
} {
	var calls []struct {
		Addr   string
		Config *tls.Config
	}
	mock.lockDialTLS.RLock()
	calls = mock.calls.DialTLS
	mock.lockDialTLS.RUnlock()
	return calls
}

// ResetDialTLSCalls reset all the calls that were made to DialTLS.
func (mock *MoqIMAPDialer) ResetDialTLSCalls() {
	mock.lockDialTLS.Lock()
	mock.calls.DialTLS = nil
	mock.lockDialTLS.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *MoqIMAPDialer) ResetCalls() {
	mock.lockDial.Lock()
	mock.calls.Dial = nil
	mock.lockDial.Unlock()

	mock.lockDialTLS.Lock()
	mock.calls.DialTLS = nil
	mock.lockDialTLS.Unlock()
}

// Ensure that MoqWatchClient does implement WatchClientInterface.
// If this is not the case, regenerate this file with mockery.
var _ WatchClientInterface = &MoqWatchClient{}

// MoqWatchClient is a mock implementation of WatchClientInterface.
//
//	func TestSomethingThatUsesWatchClientInterface(t *testing.T) {
//
//		// make and configure a mocked WatchClientInterface
//		mockedWatchClientInterface := &MoqWatchClient{
//			IdleWithFallbackFunc: func(stop <-chan struct{}, pollInterval time.Duration) error {
//				panic("mock out the IdleWithFallback method")
//			},
//			LoggedOutFunc: func() <-chan struct{} {
//				panic("mock out the LoggedOut method")
//			},
//			SelectFunc: func(name string, readOnly bool) (*imap.MailboxStatus, error) {
//				panic("mock out the Select method")
//			},
//			SetUpdatesChannelFunc: func(updates chan client.Update)  {
//				panic("mock out the SetUpdatesChannel method")
//			},
//		}
//
//		// use mockedWatchClientInterface in code that requires WatchClientInterface
//		// and then make assertions.
//
//	}
type MoqWatchClient struct {
	// IdleWithFallbackFunc mocks the IdleWithFallback method.
	IdleWithFallbackFunc func(stop <-chan struct{}, pollInterval time.Duration) error

	// LoggedOutFunc mocks the LoggedOut method.
	LoggedOutFunc func() <-chan struct{}

	// SelectFunc mocks the Select method.
	SelectFunc func(name string, readOnly bool) (*imap.MailboxStatus, error)

	// SetUpdatesChannelFunc mocks the SetUpdatesChannel method.
	SetUpdatesChannelFunc func(updates chan client.Update)

	// calls tracks calls to the methods.
	calls struct {
		// IdleWithFallback holds details about calls to the IdleWithFallback method.
		IdleWithFallback []struct {
			// Stop is the stop argument value.
			Stop <-chan struct{}
			// PollInterval is the pollInterval argument value.
			PollInterval time.Duration
		}
		// LoggedOut holds details about calls to the LoggedOut method.
		LoggedOut []struct {
		}
		// Select holds details about calls to the Select method.
		Select []struct {
			// Name is the name argument value.
			Name string
			// ReadOnly is the readOnly argument value.
			ReadOnly bool
		}
		// SetUpdatesChannel holds details about calls to the SetUpdatesChannel method.
		SetUpdatesChannel []struct {
			// Updates is the updates argument value.
			Updates chan client.Update
		}
	}
	lockIdleWithFallback  sync.RWMutex
	lockLoggedOut         sync.RWMutex
	lockSelect            sync.RWMutex
	lockSetUpdatesChannel sync.RWMutex
}

// IdleWithFallback calls IdleWithFallbackFunc.
func (mock *MoqWatchClient) IdleWithFallback(stop <-chan struct{}, pollInterval time.Duration) error {
	callInfo := struct {
		Stop         <-chan struct{}
		PollInterval time.Duration
	}{
		Stop:         stop,
		PollInterval: pollInterval,
	}
	mock.lockIdleWithFallback.Lock()
	mock.calls.IdleWithFallback = append(mock.calls.IdleWithFallback, callInfo)
	mock.lockIdleWithFallback.Unlock()
	if mock.IdleWithFallbackFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.IdleWithFallbackFunc(stop, pollInterval)
}

// IdleWithFallbackCalls gets all the calls that were made to IdleWithFallback.
// Check the length with:
//
//	len(mockedWatchClientInterface.IdleWithFallbackCalls())
func (mock *MoqWatchClient) IdleWithFallbackCalls() []struct {
	Stop         <-chan struct{}
	PollInterval time.Duration
} {
	var calls []struct {
		Stop         <-chan struct{}
		PollInterval time.Duration
	}
	mock.lockIdleWithFallback.RLock()
	calls = mock.calls.IdleWithFallback
	mock.lockIdleWithFallback.RUnlock()
	return calls
}

// ResetIdleWithFallbackCalls reset all the calls that were made to IdleWithFallback.
func (mock *MoqWatchClient) ResetIdleWithFallbackCalls() {
	mock.lockIdleWithFallback.Lock()
	mock.calls.IdleWithFallback = nil
	mock.lockIdleWithFallback.Unlock()
}

// LoggedOut calls LoggedOutFunc.
func (mock *MoqWatchClient) LoggedOut() <-chan struct{} {
	callInfo := struct {
	}{}
	mock.lockLoggedOut.Lock()
	mock.calls.LoggedOut = append(mock.calls.LoggedOut, callInfo)
	mock.lockLoggedOut.Unlock()
	if mock.LoggedOutFunc == nil {
		var (
			valCh <-chan struct{}
		)
		return valCh
	}
	return mock.LoggedOutFunc()
}

// LoggedOutCalls gets all the calls that were made to LoggedOut.
// Check the length with:
//
//	len(mockedWatchClientInterface.LoggedOutCalls())
func (mock *MoqWatchClient) LoggedOutCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLoggedOut.RLock()
	calls = mock.calls.LoggedOut
	mock.lockLoggedOut.RUnlock()
	return calls
}

// ResetLoggedOutCalls reset all the calls that were made to LoggedOut.
func (mock *MoqWatchClient) ResetLoggedOutCalls() {
	mock.lockLoggedOut.Lock()
	mock.calls.LoggedOut = nil
	mock.lockLoggedOut.Unlock()
}

// Select calls SelectFunc.
func (mock *MoqWatchClient) Select(name string, readOnly bool) (*imap.MailboxStatus, error) {
	callInfo := struct {
		Name     string
		ReadOnly bool
	}{
		Name:     name,
		ReadOnly: readOnly,
	}
	mock.lockSelect.Lock()
	mock.calls.Select = append(mock.calls.Select, callInfo)
	mock.lockSelect.Unlock()
	if mock.SelectFunc == nil {
		var (
			mailboxStatus *imap.MailboxStatus
			err           error
		)
		return mailboxStatus, err
	}
	return mock.SelectFunc(name, readOnly)
}

// SelectCalls gets all the calls that were made to Select.
// Check the length with:
//
//	len(mockedWatchClientInterface.SelectCalls())
func (mock *MoqWatchClient) SelectCalls() []struct {
	Name     string
	ReadOnly bool
} {
	var calls []struct {
		Name     string
		ReadOnly bool
	}
	mock.lockSelect.RLock()
	calls = mock.calls.Select
	mock.lockSelect.RUnlock()
	return calls
}

// ResetSelectCalls reset all the calls that were made to Select.
func (mock *MoqWatchClient) ResetSelectCalls() {
	mock.lockSelect.Lock()
	mock.calls.Select = nil
	mock.lockSelect.Unlock()
}

// SetUpdatesChannel calls SetUpdatesChannelFunc.
func (mock *MoqWatchClient) SetUpdatesChannel(updates chan client.Update) {
	callInfo := struct {
		Updates chan client.Update
	}{
		Updates: updates,
	}
	mock.lockSetUpdatesChannel.Lock()
	mock.calls.SetUpdatesChannel = append(mock.calls.SetUpdatesChannel, callInfo)
	mock.lockSetUpdatesChannel.Unlock()
	if mock.SetUpdatesChannelFunc == nil {
		return
	}
	mock.SetUpdatesChannelFunc(updates)
}

// SetUpdatesChannelCalls gets all the calls that were made to SetUpdatesChannel.
// Check the length with:
//
//	len(mockedWatchClientInterface.SetUpdatesChannelCalls())
func (mock *MoqWatchClient) SetUpdatesChannelCalls() []struct {
	Updates chan client.Update
} {
	var calls []struct {
		Updates chan client.Update
	}
	mock.lockSetUpdatesChannel.RLock()
	calls = mock.calls.SetUpdatesChannel
	mock.lockSetUpdatesChannel.RUnlock()
	return calls
}

// ResetSetUpdatesChannelCalls reset all the calls that were made to SetUpdatesChannel.
func (mock *MoqWatchClient) ResetSetUpdatesChannelCalls() {
	mock.lockSetUpdatesChannel.Lock()
	mock.calls.SetUpdatesChannel = nil
	mock.lockSetUpdatesChannel.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *MoqWatchClient) ResetCalls() {
	mock.lockIdleWithFallback.Lock()
	mock.calls.IdleWithFallback = nil
	mock.lockIdleWithFallback.Unlock()

	mock.lockLoggedOut.Lock()
	mock.calls.LoggedOut = nil
	mock.lockLoggedOut.Unlock()

	mock.lockSelect.Lock()
	mock.calls.Select = nil
	mock.lockSelect.Unlock()

	mock.lockSetUpdatesChannel.Lock()
	mock.calls.SetUpdatesChannel = nil
	mock.lockSetUpdatesChannel.Unlock()
}
